### ISSUE TITLE
FEST tests not running cleanly

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#374]
Just ran all the FEST tests and got these 2 failures:

```
java.lang.AssertionError: <'<html>
  <head>
 SNIP
'> should contain the String:<'Step 1 - Download and install'>
    at org.fest.assertions.Fail.failure(Fail.java:206)
    at org.fest.assertions.Assert.failure(Assert.java:141)
    at org.fest.assertions.StringAssert.contains(StringAssert.java:237)
    at org.multibit.hd.ui.fest.use_cases.sidebar.help.SelectGettingStartedUseCase.execute(SelectGettingStartedUseCase.java:63)
    at org.multibit.hd.ui.fest.requirements.HelpScreenRequirements.verifyUsing(HelpScreenRequirements.java:28)
    at org.multibit.hd.ui.fest.MultiBitHDFestTest.verifyHelpScreen(MultiBitHDFestTest.java:307)
```
and

```
org.fest.swing.exception.ComponentLookupException: Unable to find component using matcher org.fest.swing.core.NameMatcher[name='TREZOR_CREATE_WALLET_CONFIRM_WORD.trezor_display', type=javax.swing.text.JTextComponent, requireShowing=true].
SNIP
org.multibit.hd.ui.fest.use_cases.hardware_wallet.TrezorEnterNextWordUseCase.execute(TrezorEnterNextWordUseCase.java:45)
    at org.multibit.hd.ui.fest.requirements.CreateTrezorHardwareWalletColdStartRequirements.verifyUsing(CreateTrezorHardwareWalletColdStartRequirements.java:65)
    at org.multibit.hd.ui.fest.MultiBitHDFestTest.verifyCreateTrezorHardwareWallet_ColdStart(MultiBitHDFestTest.java:397)
```

**Comment by gary-rowe** [comment]
The recent pushes to #364 show FEST tests passing now. Can you verify and close if OK?

**Comment by bitcoin-solutions** [comment]
FEST tests running cleanly. Closing.
