### ISSUE TITLE
Help always falling over to local help

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#394]
The help being shown is always the locally stored help.
For instance the 'How to install' article has been updated but isn't shown.

This is even after a 'repair wallet' to update the SSL cert

Seeing the error:

```
[2015-02-05 15:30:27,586] WARN  [AWT-EventQueue-0] o.m.h.u.v.s.h.HelpScreenView - Problem with MultiBit.org so switching to internal help ! javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.7.0_72]
! at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884) ~[na:1.7.0_72]
! at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276) ~[na:1.7.0_72]
! at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270) ~[na:1.7.0_72]
! at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1439) ~[na:1.7.0_72]
! at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209) ~[na:1.7.0_72]
! at sun.security.ssl.Handshaker.processLoop(Handshaker.java:878) ~[na:1.7.0_72]
! at sun.security.ssl.Handshaker.process_record(Handshaker.java:814) ~[na:1.7.0_72]
! at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016) ~[na:1.7.0_72]
! at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312) ~[na:1.7.0_72]
! at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1339) ~[na:1.7.0_72]
! at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1323) ~[na:1.7.0_72]
! at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563) ~[na:1.7.0_72]
! at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[na:1.7.0_72]
! at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300) ~[na:1.7.0_72]
! at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.7.0_72]
! at org.multibit.hd.core.managers.SSLManager.getContentAsString(SSLManager.java:197) ~[multibit-hd.jar:na]
! at org.multibit.hd.ui.views.screens.help.HelpScreenView.createBrowser(HelpScreenView.java:249) [multibit-hd.jar:na]
! at org.multibit.hd.ui.views.screens.help.HelpScreenView.initialiseScreenViewPanel(HelpScreenView.java:194) [multibit-hd.jar:na]
! at org.multibit.hd.ui.views.screens.AbstractScreenView.getScreenViewPanel(AbstractScreenView.java:112) [multibit-hd.jar:na]
! at org.multibit.hd.ui.views.DetailView.onShowDetailScreen(DetailView.java:113) [multibit-hd.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_72]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_72]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_72]
! at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_72]
! at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [multibit-hd.jar:na]
! at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [multibit-hd.jar:na]
! at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [multibit-hd.jar:na]
! at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [multibit-hd.jar:na]
! at com.google.common.eventbus.EventBus.post(EventBus.java:275) [multibit-hd.jar:na]
! at org.multibit.hd.ui.events.view.ViewEvents.fireWizardHideEvent(ViewEvents.java:334) [multibit-hd.jar:na]
! at org.multibit.hd.ui.views.wizards.AbstractWizard$8.run(AbstractWizard.java:453) [multibit-hd.jar:na]
! at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312) [na:1.7.0_72]
! at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733) [na:1.7.0_72]
! at java.awt.EventQueue.access$200(EventQueue.java:103) [na:1.7.0_72]
! at java.awt.EventQueue$3.run(EventQueue.java:694) [na:1.7.0_72]
! at java.awt.EventQueue$3.run(EventQueue.java:692) [na:1.7.0_72]
! at java.security.AccessController.doPrivileged(Native Method) [na:1.7.0_72]
! at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) [na:1.7.0_72]
! at java.awt.EventQueue.dispatchEvent(EventQueue.java:703) [na:1.7.0_72]
! at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_72]
! at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_72]
! at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_72]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_72]
! at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_72]
! at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_72]
Caused by: ! sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385) ~[na:1.7.0_72]
! at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.7.0_72]
! at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.7.0_72]
! at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326) ~[na:1.7.0_72]
! at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[na:1.7.0_72]
! at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126) ~[na:1.7.0_72]
! at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1421) ~[na:1.7.0_72]
!... 41 common frames omitted
Caused by: ! sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
! at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196) ~[na:1.7.0_72]
! at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268) ~[na:1.7.0_72]
! at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380) ~[na:1.7.0_72]
!... 47 common frames omitted
```

**Comment by gary-rowe** [comment]
Would also be useful practice to update the internal help (see README) to the latest from the release-4.0.0 branch of the website repo.

**Comment by bitcoin-solutions** [comment]
Just tried to reproduce this error without success - got the correct online help (e.g. new install page).

**Comment by bitcoin-solutions** [comment]
I was seeing the same PKIX errors so it was genuine. Perhaps modify the internal help to trigger a refresh of the CA certs in the background if the MultiBit.org fails?

**Comment by bitcoin-solutions** [comment]
I've added the need to update the local help to the multibit-installer README checklist.
Also added a background refresh of the SSL certs if the browser cannot reach multibit.org and has to fallback to the local help.
You can test this by either deleting the cert store or putting in an old one (e.g. one with the pre-wildcard subdomain multibit.org cert).

Live image resizing - not sure we can do much about that using the JEditorPane "browser".

Awaiting review and closing

**Comment by gary-rowe** [comment]
Regarding the image resizing we could:

* do something similar to `HelpScreenView.populateImageCache` when the HTMLEditorKit is managing its InputStreams. 
* adjust HTML `<img>` tags on the fly to contain inline `style="width:20%; height: auto"` entries.
* add some simple CSS rules in `createEditorKit`
* finally, force the screenshot images to be "internal help" size from the server and not have a "supersize" version for people with large screens browsing the help in an external browser (this is the more correct approach but will involve regularly running a resize script before pushing content to the site repo)

It's worth a little experimentation in this class just to add that extra polish.

**Comment by gary-rowe** [comment]
OK, we'll leave the image resize for another day. Observed the download from the main site working correctly.

Closing.

**Comment by jim618** [comment]
In MBHD 0.0.7beta the help is STILL falling over to the local help.
In the logs you can see it falling over with the SSL connection and it correctly redownloads all the SSL certs. But then if you open it up again it STILL falls over to the local help

**Comment by gary-rowe** [comment]
The fix for this should include taking a copy of the Windows Java 8 `cacerts` and using them as the basis for the MultiBit HD trust store. This will ensure that a common set of CAs is available for BIP 70 signature verification.

**Comment by jim618** [comment]
Copying the Windows Java 8 cacerts is raised as: #477 so marking this as 'Awaiting issue'.
It's also dependent on us getting better SSL certs - we have EV certs from digicert on the way (still in the verification stage though which is causing a delay).

**Comment by jim618** [comment]
Now that #477 is done I retested the help.
I can see in Little Snitch that (once it repairs certs) it is hitting the multibit.org server for help.

Closing.
