### ISSUE TITLE
BIP44 soft wallet falling back to rolling backups

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#428]
Made a BIP44 soft wallet (Mycelium compatible) and have seen this occur after a full synch, exit, unlock sequence:
```
KeyChainGroup#fromProtobufEncrypted There are 603 keys.
[2015-02-24 22:02:11,202] ERROR [safe-fixed-unlock-wallet-0] o.m.h.c.m.WalletManager - WalletManager error: java.lang.IllegalArgumentException No key found for absolute path M/44H/0H/1/1. ! java.lang.IllegalArgumentException: No key found for absolute path M/44H/0H/1/1.
! at org.bitcoinj.crypto.DeterministicHierarchy.get(DeterministicHierarchy.java:94) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:761) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.DeterministicKeyChain.getKeyByPath(DeterministicKeyChain.java:756) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.KeyChainGroup.createCurrentKeysMap(KeyChainGroup.java:839) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.wallet.KeyChainGroup.fromProtobufEncrypted(KeyChainGroup.java:723) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:418) ~[bitcoinj-core-0.13-alice-SNAPSHOT.jar:na]
! at org.multibit.hd.core.managers.WalletManager.loadWalletFromFile(WalletManager.java:812) [classes/:na]
! at org.multibit.hd.core.managers.WalletManager.loadFromWalletDirectory(WalletManager.java:916) [classes/:na]
! at org.multibit.hd.core.managers.WalletManager.openWalletFromWalletId(WalletManager.java:241) [classes/:na]
! at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.checkPasswordAndLoadWallet(CredentialsWizardModel.java:749) [classes/:na]
! at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.access$500(CredentialsWizardModel.java:59) [classes/:na]
! at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$13.call(CredentialsWizardModel.java:677) [classes/:na]
! at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$13.call(CredentialsWizardModel.java:669) [classes/:na]
! at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_51]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_51]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_51]
! at java.lang.Thread.run(Thread.java:744) [na:1.7.0_51]
```

The report screen correctly shows a fallback to a rolling backup and the wallet syncs back into position but it is annoying.

**Comment by gary-rowe** [comment]
This is identical to #368 which has been deferred to Release 0.1. Closing as duplicate.
