### ISSUE TITLE
CrashReporter: Pressing return when showing QR code in Payment request crashes app

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#529]
CrashReporter gives exception:
```
o.m.h.c.e.ExceptionHandler - Uncaught exception ! java.lang.IllegalStateException: LightBoxPopover should never be called twice
! at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[guava-16.0.1.jar:na]
! at org.multibit.hd.ui.views.components.Panels.showLightBoxPopover(Panels.java:305) ~[classes/:na]
! at org.multibit.hd.ui.views.wizards.payments.PaymentRequestDetailPanelView$1.actionPerformed(PaymentRequestDetailPanelView.java:283) ~[classes/:na]
```

**Comment by gary-rowe** [comment]
Already proving useful...

**Comment by jim618** [comment]
Pressing return whilst the QR code popover is being shown now closes the popover.

Awaiting review and closing

**Comment by jim618** [comment]
Also fixed similar bug on the 'Request Bitcoin' screen that I missed previously

**Comment by gary-rowe** [comment]
Verified working.

Closing.
