### ISSUE TITLE
CrashReporter: Delete a PaymentRequest in Payments

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#532]
Saw this stack trace when deleting a payment request:
```
[2015-04-20 13:11:05,676] ERROR [AWT-EventQueue-0] o.m.h.c.e.ExceptionHandler - Uncaught exception ! java.lang.IndexOutOfBoundsException: Index: 26, Size: 26
! at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[na:1.7.0_72]
! at java.util.ArrayList.get(ArrayList.java:411) ~[na:1.7.0_72]
! at org.multibit.hd.ui.views.screens.payments.PaymentsScreenView.getPaymentDataForSelectedTableRow(PaymentsScreenView.java:353) ~[multibit-hd.jar:na]
SNIP
[2015-04-20 13:11:05,723] DEBUG [AWT-EventQueue-0] o.m.h.u.v.s.p.PaymentsScreenView - getExportAction : selectedTableRow = 3, selectedModelRow = 3 
[2015-04-20 13:11:05,727] DEBUG [AWT-EventQueue-0] o.m.h.u.v.s.p.PaymentsScreenView - getExportAction : selectedTableRow = 3, selectedModelRow = 3 
```

**Comment by jim618** [comment]
Added more range checking in PaymentsScreenView#getPaymentDataForSelectedTableRow

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working.

Closing.
