### ISSUE TITLE
CrashReporter: Press next in send without adding anything

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#535]
If you press Next in the Send enter amount screen without entering ANYTHING you get the crash report:
```
[2015-04-22 12:55:47,135] ERROR [AWT-EventQueue-1] o.m.h.c.e.ExceptionHandler - Uncaught exception ! java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
! at com.google.common.base.Absent.get(Absent.java:47) ~[guava-16.0.1.jar:na]
! at org.multibit.hd.ui.views.wizards.send_bitcoin.SendBitcoinWizardModel.prepareTransaction(SendBitcoinWizardModel.java:402) ~[classes/:na]
! at org.multibit.hd.ui.views.wizards.send_bitcoin.SendBitcoinWizardModel.showNext(SendBitcoinWizardModel.java:159) ~[classes/:na]

```

**Comment by jim618** [comment]
Tightened up on Next being enabled and also put in some checks in the model Next handler which redirect back to the enter amount page (just in case).

Next is only enabled when the network is ok, there is a recipient and an amount has been entered.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
