### ISSUE TITLE
One FEST test failing: verifySendRequestScreen

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#554]
I just ran the FEST tests and there was one failure:

verifySendRequestScreen

java.lang.AssertionError: <'Trezor "Example" attached. Do you want to use it ?'> should contain the String:<'Please donate to MultiBit'>
	at org.fest.assertions.Fail.failure(Fail.java:206)
	at org.fest.assertions.Assert.failure(Assert.java:141)
	at org.fest.assertions.StringAssert.contains(StringAssert.java:237)
	at org.multibit.hd.ui.fest.use_cases.AbstractFestUseCase.assertLabelContainsValue(AbstractFestUseCase.java:232)
	at org.multibit.hd.ui.fest.use_cases.sidebar.send_request.send.SendDisplayUntrustedPaymentRequestUseCase.execute(SendDisplayUntrustedPaymentRequestUseCase.java:43)
	
I think there were two alerts in a stack and the test is looking for the wrong one (couldn't swear to it though as this is just what I noticed when it ran).

**Comment by jim618** [comment]
Updated FEST text - Next button in Send progress is enabled rather than disabled as per old test.
It's the MultiBitFESTTest#verifySendRequestScreen() test suite.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
