### ISSUE TITLE
Bad position: -1

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#628]
Failure in Clipboard - most likely pasting in the Wallet words confirm window

**Comment by gary-rowe** [comment]
If it's possible to add an exception that would be handy. Possibly related to #167 if it's on Linux.

**Comment by jim618** [comment]
Multiple exceptions:
"_source": {
"@timestamp": "2015-06-26T03:14:35.798+04:30",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "java.lang.IllegalArgumentException: bad position: -1 at javax.swing.text.JTextComponent.setCaretPosition(JTextComponent.java:1678) ~[na:1.7.0_80] at javax.swing.text.DefaultEditorKit$BeginLineAction.actionPerformed(DefaultEditorKit.java:1958) ~[na:1.7.0_80] at javax.swing.text.DefaultEditorKit$SelectLineAction.actionPerformed(DefaultEditorKit.java:2192) ~


"_source": {
"@timestamp": "2015-06-21T19:19:48.628-07:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.util.TimSort.mergeHi(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.mergeAt(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.mergeForceCollapse(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
 at java.util.Arrays.sort(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.DataTransferer.setToSortedDataFlavorArray(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.ClipboardTransferable.<init>(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.SunClipboard.getContents(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction.actionPerformedImpl(Unknown Source) ~[na:1.7.0_80]

**Comment by gary-rowe** [comment]
I've tried to replicate the "bad positoin: -1" on OS X 10.10.3 (as per the report) but can't. It looks suspiciously like an [old Netbeans bug](https://netbeans.org/bugzilla/show_bug.cgi?id=165713) which proved impossible to replicate.

I'm going to close this unless we start seeing repeats.

**Comment by gary-rowe** [comment]
Just had this from the current latest 0.1.3:

MultiBit HD version: 0.1.3
Operating system: 64 6.3 Windows 8.1

```
java.lang.IllegalArgumentException: bad position: -1
        at javax.swing.text.JTextComponent.setCaretPosition(Unknown Source) ~[na:1.7.0_80]
        at javax.swing.text.DefaultEditorKit$BeginLineAction.actionPerformed(Unknown Source) ~[na:1.7.0_80]
        at javax.swing.text.DefaultEditorKit$SelectLineAction.actionPerformed(Unknown Source) ~[na:1.7.0_80]
        at javax.swing.text.DefaultCaret.mouseClicked(Unknown Source) ~[na:1.7.0_80]
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source) ~[na:1.7.0_80]
        at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.7.0_80]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.7.0_80]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventQueue.access$300(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[na:1.7.0_80]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.7.0_80]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.7.0_80]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.7.0_80]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.7.0_80]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_80]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.7.0_80]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.7.0_80]
```

This is one to add to the "ignore list" since we can't trap it any other way.

**Comment by jim618** [comment]
Added to ExceptionHandler#isBenign.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Looks good to me. Closing.
