### ISSUE TITLE
History load failure

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#629]
Looks like a history load error:
"@timestamp": "2015-06-22T16:23:35.060-05:00",
"level": "ERROR",
"thread_name": "safe-fixed-unlock-wallet-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "org.multibit.hd.core.exceptions.HistoryLoadException: Could not parse input stream to protobuf
 at org.multibit.hd.core.store.HistoryProtobufSerializer.readHistoryEntries(HistoryProtobufSerializer.java:93) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.PersistentHistoryService.loadHistory(PersistentHistoryService.java:177) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.PersistentHistoryService.initialise(PersistentHistoryService.java:98) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.PersistentHistoryService.<init>(PersistentHistoryService.java:78) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.CoreServices.getOrCreateHistoryService(CoreServices.java:577) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.checkPasswordAndLoadWallet(CredentialsWizardModel.java:781) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.access$500(CredentialsWizardModel.java:57) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$10.call(CredentialsWizardModel.java:711)

**Comment by gary-rowe** [comment]
We'll need better error handling here (and the related Contacts and Payments streams) with a possible fallback to a local backup.

**Comment by gary-rowe** [comment]
The History error handling was different to Contacts and Payments in that it handed over an error to the crash reporter rather than passing it up the stack. However the problem of correctly handling it remains.

**Comment by jim618** [comment]
Backups for history/contacts/payments is already raised as #407

**Comment by gary-rowe** [comment]
Given that the longer term fix is currently scheduled for Release 0.2 there's no need for this issue to remain open.

Ready for review and close.

**Comment by jim618** [comment]
This is now OK but #407 needs to be implemented.
If there is a problem with the history the user sees a 'the password cannot unlock the wallet' rather than the crash reporter. This is better but needs a bit more work.

**Comment by jim618** [comment]
Reopened as still seeing:

"@timestamp": "2015-06-30T21:28:19.670+02:00",
"level": "ERROR",
"thread_name": "safe-fixed-unlock-wallet-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "org.multibit.hd.core.exceptions.HistoryLoadException: Could not parse input stream to protobuf
 at org.multibit.hd.core.store.HistoryProtobufSerializer.readHistoryEntries(HistoryProtobufSerializer.java:93) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.PersistentHistoryService.loadHistory(PersistentHistoryService.java:177) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.PersistentHistoryService.initialise(PersistentHistoryService.java:98) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.PersistentHistoryService.<init>(PersistentHistoryService.java:78) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.CoreServices.getOrCreateHistoryService(CoreServices.java:577) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.checkPasswordAndLoadWallet(CredentialsWizardModel.java:781) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.access$500(CredentialsWizardModel.java:57) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$10.call(CredentialsWizardModel.java:711) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$10.call(CredentialsWizardModel.java:703)

**Comment by jim618** [comment]
Should be fixed by #647 

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Now that history is gone this should also disappear. Closing.
