### ISSUE TITLE
CrashReporter: Wallet dashboard not showing

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#631]
"_source": {
"@timestamp": "2015-06-25T10:08:55.020+02:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
 at com.google.common.base.Absent.get(Absent.java:47) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.components.wallet_detail.WalletDetailModel.update(WalletDetailModel.java:58) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.components.wallet_detail.WalletDetailModel.<init>(WalletDetailModel.java:38) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.components.Components.newWalletDetailMaV(Components.java:60) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.wallet_details.WalletDetailsPanelView.initialiseContent(WalletDetailsPanelView.java:76) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.AbstractWizardPanelView.getWizardScreenPanel(AbstractWizardPanelView.java:249) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.AbstractWizard.show(AbstractWizard.java:179) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.AbstractWizard.<init>(AbstractWizard.java:132) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.AbstractWizard.<init>(AbstractWizard.java:80) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.wallet_details.WalletDetailsWizard.<init>(WalletDetailsWizard.java:21) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.Wizards.newWalletDetailsWizard(Wizards.java:533) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.screens.manage_wallet.ManageWalletScreenView$2.actionPerformed(ManageWalletScreenView.java:161) ~[multibit-hd.jar:na]
 at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.7.0_80]

**Comment by jim618** [comment]
Hardened code for if walletService is not present.
Awaiting review and closing.

**Comment by gary-rowe** [comment]
Looks good to me.

Closing.
