### ISSUE TITLE
Request bitcoin screen failure

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#644]
"@timestamp": "2015-06-26T18:45:00.310-04:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
 at com.google.common.base.Absent.get(Absent.java:47) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.newPanelModel(RequestBitcoinEnterDetailsPanelView.java:104) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.AbstractWizardPanelView.<init>(AbstractWizardPanelView.java:123) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.<init>(RequestBitcoinEnterDetailsPanelView.java:84) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinWizard.populateWizardViewMap(RequestBitcoinWizard.java:28) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.AbstractWizard.<init>(AbstractWizard.java:117) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.AbstractWizard.<init>(AbstractWizard.java:80) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinWizard.<init>(RequestBitcoinWizard.java:22) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.Wizards.newRequestBitcoinWizard(Wizards.java:177) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.screens.wallet.SendRequestScreenView$2.actionPerformed(SendRequestScreenView.java:102) ~[multibit-hd.jar:na]
 at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.7.0_80]
 at

**Comment by jim618** [comment]
Added in more optional checking.
Awaiting code review and closing

**Comment by gary-rowe** [comment]
Any idea how the user managed to get into the situation where they could access the request button without a WalletService being present?

Either way, this will give a better chance at recovery so closing.
