### ISSUE TITLE
Clipboard failure in Send amount

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#645]
"_source": {
"@timestamp": "2015-06-30T14:15:31.334+03:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception",
"stack_trace": "java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.util.TimSort.mergeHi(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.mergeAt(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.mergeCollapse(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
 at java.util.Arrays.sort(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.DataTransferer.setToSortedDataFlavorArray(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.ClipboardTransferable.<init>(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.SunClipboard.getContents(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction.actionPerformedImpl(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction.access$700(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction$1.run(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction$1.run(Unknown Source) ~[na:1.7.0_80]
 at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[na:1.7.0_80]
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction$2.run(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction$2.run(Unknown Source) ~[na:1.7.0_80]
 at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
 at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.TransferHandler$TransferAction.actionPerformed(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.text.JTextComponent.invokeAction(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.text.JTextComponent.paste(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.text.DefaultEditorKit$PasteAction.actionPerformed(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.SwingUtilities.notifyAction(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.JComponent.processKeyBinding(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.JComponent.processKeyBindings(Unknown Source) ~[na:1.7.0_80]
 at javax.swing

**Comment by jim618** [comment]
This is quite common in the error reports

**Comment by jim618** [comment]
Best diagnostic I found was here:
https://www.java.net/node/700601
FocusTraversalPolicy problem.

Added
```
      // Fix for clipboard failure - https://github.com/bitcoin-solutions/multibit-hd/issues/645
      // Suggested by https://www.java.net/node/700601
      System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");
```

Not reproducible hence only a probable fix.

Awaiting code review and closing.

**Comment by gary-rowe** [comment]
No real way to test this outside of just using it. Closing.

**Comment by gary-rowe** [comment]
This has appeared again in #635 which continues this issue.
