### ISSUE TITLE
Right click in address field crashed multibit

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#649]
"When i rightclicked in the textbox where you are supposed to insert the address to send bitcoins to it chrashed..",

**Comment by gary-rowe** [comment]
Any stack trace to work with?

**Comment by jim618** [comment]
"_source": {
"@timestamp": "2015-07-03T18:17:06.580+02:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception. Proceeding to show Error Reporting dialog...",
"stack_trace": "java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.util.TimSort.mergeHi(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.mergeAt(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.mergeCollapse(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
 at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
 at java.util.Arrays.sort(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.DataTransferer.setToSortedDataFlavorArray(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.ClipboardTransferable.<init>(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.datatransfer.SunClipboard.getContents(Unknown Source) ~[na:1.7.0_80]
 at org.multibit.hd.ui.utils.ClipboardUtils.pasteStringFromClipboard(ClipboardUtils.java:95) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.components.enter_recipient.EnterRecipientView.performPaste(EnterRecipientView.java:236) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.components.enter_recipient.EnterRecipientView.access$000(EnterRecipientView.java:37) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.components.enter_recipient.EnterRecipientView$4.actionPerformed(EnterRecipientView.java:230) ~[multibit-hd.jar:na]
 at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.7.0_80]

**Comment by jim618** [comment]
Same error as in #645 which has a probable fix.
Marking as awaiting issue

**Comment by gary-rowe** [comment]
Have we seen any more "TimSort" issues in 0.1.2 error reports?

**Comment by jim618** [comment]
Yes.
e.g:

New error report uploaded. Id: 4808d71

MultiBit HD version: 0.1.2
Operating system: 64 6.3 Windows 8.1

User notes length: 2

Number of stack traces: 1
First stack trace:
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(Unknown Source) ~[na:1.7.0_80]
	at java.util.TimSort.mergeAt(Unknown Source) ~[na:1.7.0_80]
	at java.util.TimSort.mergeCollapse(Unknown Source) ~[na:1.7.0_80]
	at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
	at java.util.TimSort.sort(Unknown Source) ~[na:1.7.0_80]
	at java.util.Arrays.sort(Unknown Source) ~[na:1.7.0_80]
	at sun.awt.datatransfer.DataTransferer.setToSortedDataFlavorArray(Unknown Source) ~[na:1.7.0_80]
	at sun.awt.datatransfer.ClipboardTransferable.<init>(Unknown Source) ~[na:1.7.0_80]
	at sun.awt.datatransfer.SunClipboard.getContents(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.TransferHandler$TransferAction.actionPerformedImpl(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.TransferHandler$TransferAction.access$700(Unknown Source) ~[na:1.7.0

**Comment by jim618** [comment]
@gary-rowe has put in some reordering in #701 to (probably) help with the TimSort error.

I'll mark as 'Awaiting review' - close it if you think the fix is good enough. We'll have to see what the error reports say with 0.1.3 I think.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
In conjuction with #708 this will be either fixed (unlikely due to JVM behaviour) or ignored.

Closing.
