### ISSUE TITLE
Cannot open YAML - not readable

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#653]
Raised by gigantic in bitcointalk:

Hi
I am getting an error every time i am starting the multibit HD Client,
I have the latest Java version,

This is from the error log-

Code:
unacceptable character ' ' (0x0) special characters are not allowed
in "'reader'", position 0
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:93)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:192)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.<init>(YAMLParser.java:147)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory._createParser(YAMLFactory.java:513)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:326)
	at com.fasterxml.jackson.dataformat.yaml.YAMLFactory.createParser(YAMLFactory.java:14)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2192)
	at org.multibit.hd.core.config.Yaml.readYaml(Yaml.java:54)
	at org.multibit.hd.core.services.CoreServices.bootstrap(CoreServices.java:149)
	at org.multibit.hd.ui.MultiBitHD.start(MultiBitHD.java:92)
	at org.multibit.hd.ui.MultiBitHD.main(MultiBitHD.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.exe4j.runtime.WinLauncher.main(Unknown Source)
	at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)

**Comment by jim618** [comment]
Extra info: The error was after i clicked the Exit button without logging to the wallet, not sure if that's helpful...

**Comment by gary-rowe** [comment]
We should add some extra checking during startup and revert to a default configuration if we see problems. Since there's nothing the user can do I don't think we need to issue an alert indicating the problem.

**Comment by gary-rowe** [comment]
The fall back position for a failed YAML read/write is to use a default `Configuration`. If we start getting lots of problems from users about "not saving my settings" then we can look into providing a delayed alert indicating that a problem was detected. 

Ready for review and close.

**Comment by jim618** [comment]
LGTM. Closing
