### ISSUE TITLE
DNS seed lookup failure

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#667]
,
{
"_index": "error-report-entries-4bf6d19",
"_type": "log-entry",
"_id": "652",
"_score": null,
"_source": {
"@timestamp": "2015-07-14T21:03:02.456+00:00",
"level": "ERROR",
"thread_name": "DNS seed lookups",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception. Proceeding to show Error Reporting dialog...",
"stack_trace": "java.lang.IllegalMonitorStateException: null at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:155) ~[na:1.7.0_79] at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1260) ~[na:1.7.0_79] at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:460) ~[na:1.7.0_79] at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:449) ~[na:1.7.0_79] at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068) ~[na:1.7.0_79] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:1.7.0_79] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_79] at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27) ~[multibit-hd.jar:na] at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79] ",
"level_value": 40000,
"@version": 1
},
"sort": [
1436907782456

**Comment by jim618** [comment]
Looks like a bitcoinj layer error so bumped into 0.1.4 for dealing with later
