### ISSUE TITLE
Sign message failure

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#668]
```
"_source": {
"@timestamp": "2015-07-18T10:19:55.902+03:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception. Proceeding to show Error Reporting dialog...",
"stack_trace": "java.lang.IllegalStateException: Optional.get() cannot be called on an absent value
 at com.google.common.base.Absent.get(Absent.java:47) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.Wizards.newSignMessageWizard(Wizards.java:244) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.screens.tools.ToolsScreenView$3.actionPerformed(ToolsScreenView.java:101) ~[multibit-hd.jar:na]
 at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.7.0_80]
 at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.7.0_80]
```

**Comment by jim618** [comment]
I have added in some defensive code in WalletMode to trap this error.
I think the problem is that the status of the hardwareWalletService optional changes racily.
I've caught the IllegalArgumentException and returned a Standard wallet mode rather than throw it out to the ErrorReporter.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Seems sensible. Closing.
