### ISSUE TITLE
Could not empty wallet

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#670]
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.services.BitcoinNetworkService",
"message": "Could not complete the transaction without signing",
"stack_trace": "org.bitcoinj.core.Wallet$CouldNotAdjustDownwards: null
 at org.bitcoinj.core.Wallet.completeTx(Wallet.java:3730) ~[multibit-hd.jar:na]
 at org.multibit.hd.core.services.BitcoinNetworkService.completeWithoutSigning(BitcoinNetworkService.java:902) [multibit-hd.jar:na]
 at org.multibit.hd.core.services.BitcoinNetworkService.prepareTransaction(BitcoinNetworkService.java:765) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.prepareTransaction(EmptyWalletWizardModel.java:280) [multibit-hd.jar:na]
 at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.showNext(EmptyWalletWizardModel.java:118) [multibit-hd.jar:na]

**Comment by gary-rowe** [comment]
Looks like the wallet didn't have enough funds to allow it to be emptied. We'll need a warning for this.

**Comment by jim618** [comment]
Presuably caused by too much dust

**Comment by jim618** [comment]
BitcoinNetworkService has already had it's error handling tweaked so that:
+ the error is logged but no stacktrace is printed
+ the user gets a useful message.

Nothing to do so closing.
