### ISSUE TITLE
No wallet is present at ContactService creation

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#675]
"2015-07-18T10:15:04.094+03:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "'currentWalletSummary' must be present. No wallet is present.",
"stack_trace": "java.lang.IllegalStateException: 'currentWalletSummary' must be present. No wallet is present.
 at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[multibit-hd.jar:na]
 at org.multibit.hd.core.services.CoreServices.getCurrentContactService(CoreServices.java:544) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.screens.Screens.newScreen(Screens.java:74) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.DetailView.onShowDetailScreen(DetailView.java:77) ~[multibit-hd.jar:na]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_80]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_80]
 at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_80]
 at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[multibit-hd.jar:na]
 at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[multibit-hd.jar:na]
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [multibit-hd.jar:na]
 at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [multibit-hd.jar:na]
 at

**Comment by gary-rowe** [comment]
This needs to be in 0.1.3 since somehow the Contacts are showing without a wallet being present.

**Comment by gary-rowe** [comment]
Sequence from the logs is

* Startup to password screen
* Click Restore
* See "Welcome select wallet" (exiting / standard)
* Lightbox is hidden (possible race condition)
* Invisible exceptions in ManageWalletScreenView.initialiseScreenView()
* User randomly reaches SignMessage and triggers error reporter

**Comment by gary-rowe** [comment]
I saw an NPE when fixing #657 (see b13c2aa6ddc29bb312f65a966fb0c331e42c67c8) which triggered a failed light box. This has been fixed and may as a side-effect fix this as well.

Awaiting issue #657.

**Comment by jim618** [comment]
Closed as #657 Is now closed.
