### ISSUE TITLE
BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData in StripedTable

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#677]
```
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception. Proceeding to show Error Reporting dialog...",
"stack_trace": "java.lang.ClassCastException: sun.awt.image.BufImgSurfaceData cannot be cast to sun.java2d.xr.XRSurfaceData at sun.java2d.xr.XRRenderer.validateSurface(XRRenderer.java:72) ~[na:1.8.0_45] at sun.java2d.xr.XRRenderer.drawLine(XRRenderer.java:87) ~[na:1.8.0_45] at sun.java2d.SunGraphics2D.drawLine(SunGraphics2D.java:2234) ~[na:1.8.0_45] at javax.swing.plaf.synth.SynthGraphicsUtils.drawLine(SynthGraphicsUtils.java:77) ~[na:1.8.0_45] at javax.swing.plaf.synth.SynthTableUI.paintGrid(SynthTableUI.java:523) ~[na:1.8.0_45] at javax.swing.plaf.synth.SynthTableUI.paint(SynthTableUI.java:369) ~[na:1.8.0_45] at javax.swing.plaf.synth.SynthTableUI.update(SynthTableUI.java:275) ~[na:1.8.0_45] at javax.swing.JComponent.paintComponent(JComponent.java:780) ~[na:1.8.0_45] at org.multibit.hd.ui.views.components.tables.StripedTable.paintComponent(StripedTable.java:39) ~[multibit-hd.jar:na] at javax.swing.JComponent.paint(JComponent.java:1056) ~[na:1.8.0_45] at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_45] at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_45] at javax.swing.JViewport.paint(JViewport.java:728) ~[na:1.8.0_45] at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_45] at javax.swing.JComponent.paint(JComponent.java:1065) ~[na:1.8.0_45] at javax.swing.JComponent.paintChildren(JComponent.java:889) ~[na:1.8.0_45] at 
```

**Comment by gary-rowe** [comment]
This appears to be a manifestation of a known bug in Java 8 (see [7172749](https://bugs.openjdk.java.net/browse/JDK-7172749)). The user should be advised to use Java 7 to avoid it.

**Comment by jim618** [comment]
Agreed. Closing.

**Comment by jim618** [comment]
As we are still seeing this in 0.1.3 perhaps absorb this error if it is safe to do so

**Comment by gary-rowe** [comment]
Agreed. Add it to the pile of "pure Java so can't trap it" exceptions.

**Comment by jim618** [comment]
Added to list of benign exceptions in ExceptionHandler.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Code review looks good.

Closing.
