### ISSUE TITLE
Too many PeerDiscoveryExceptions cluttering up logs

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#678]
There are far too many PeerDiscoveryExceptions cluttering up the logs  and making it hard to spot other exceptions:

"message": "Peer discovery failure",
"stack_trace": "org.bitcoinj.net.discovery.PeerDiscoveryException: java.lang.UnsupportedOperationException
 at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:93) ~[multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:769) ~[multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup$5.go(PeerGroup.java:478) [multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup$5.run(PeerGroup.java:449) [multibit-hd.jar:na]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_80]
 at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27) [multibit-hd.jar:na]
 at java.lang.Thread.run(Unknown Source) [na:1.7.0_80]
 Caused by: java.lang.UnsupportedOperationException: null
 at com.subgraph.orchid.sockets.OrchidSocketImpl.setOption(OrchidSocketImpl.java:28) ~[multibit-hd.jar:na]
 at java.net.Socket.setSoTimeout(Unknown Source) ~[na:1.7.0_80]
 at com.squareup.okhttp.Connection.connect(Connection.java:154) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.OkHttpClient$1.connectAndS

**Comment by gary-rowe** [comment]
This will probably be fixed with a Bitcoinj upgrade (and raising the default logging level of Bitcoinj to `ERROR`) in `LoggingConfiguration`

**Comment by jim618** [comment]
Updated bitcoinj-alice still needs pushing to staging repo yet

**Comment by gary-rowe** [comment]
@jim618 have you pushed the updated bitcoinj-alice yet?

**Comment by gary-rowe** [comment]
Marking as awaiting issue on #652.

**Comment by jim618** [comment]
Yup - all pushed a while ago.
it is the bitcoinj-0.13-alice-0.1.3 artefact

**Comment by jim618** [comment]
Closing as nothing to do
