### ISSUE TITLE
Screen device failure

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#689]
"_index": "error-reports-4ce1113",
"_type": "log-entry",
"_id": "583",
"_score": 1,
"_source": {
"@timestamp": "2015-07-08T13:55:59.121-05:00",
"level": "ERROR",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception. Proceeding to show Error Reporting dialog...",
"stack_trace": "java.lang.ArrayIndexOutOfBoundsException: 1
 at sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.windows.WWindowPeer.updateGC(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.windows.WWindowPeer.displayChanged(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.SunDisplayChanger.notifyListeners(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.Win32GraphicsDevice.displayChanged(Unknown Source) ~[na:1.7.0_80]
 at sun.java2d.d3d.D3DGraphicsDevice.displayChanged(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.Win32GraphicsEnvironment.displayChanged(Unknown Source) ~[na:1.7.0_80]
 at sun.awt.windows.WToolkit$5.run(Unknown Source) ~[na:1.7.0_80]
 at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[na:1.7.0_80]
 at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na

**Comment by gary-rowe** [comment]
This is a similar problem to #608. Some additional information about the operating system would be helpful here.

**Comment by gary-rowe** [comment]
Looking at the nature of the error I don't think it's something we can fix. The EDT has issued an event and the JRE has incorrectly provided a default screen that is not available.

If you agree with this analysis feel free to close.

**Comment by jim618** [comment]
Yeah - I don't think we can fix this.
Closing.
