### ISSUE TITLE
No exchange rate causes NPE

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#690]
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.error_reporting.ExceptionHandler",
"message": "Uncaught exception. Proceeding to show Error Reporting dialog...",
"stack_trace": "java.lang.NullPointerException: 'exchangeRate' must be present
 at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[multibit-hd.jar:na]
 at org.multibit.hd.core.utils.Coins.toLocalAmount(Coins.java:37) ~[multibit-hd.jar:na]
 at org.multibit.hd.ui.views.components.enter_amount.EnterAmountView$4.run(EnterAmountView.java:371) ~[multibit-hd.jar:na]
 at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[na:1.7.0_80]

**Comment by gary-rowe** [comment]
Trivial fix so worth putting into 0.1.3.

**Comment by jim618** [comment]
I've put in checks for all usages of Coins.toLocalAmount to check for a null exchange rate.
Awaiting code review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
