### ISSUE TITLE
issues when compiling multibit-hd on windows7 with JDK1.7

### ISSUE THREAD

**Issue by lamar8** [bitcoin-solutions/multibit-hd#695]
I want to build it on windows7 ,but failed ,is there anyone can heip me?

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MultiBit HD ........................................ SUCCESS [  6.820 s]
[INFO] MultiBit HD Core ................................... FAILURE [02:56 min]
[INFO] MultiBit HD Swing .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:03 min
[INFO] Finished at: 2015-08-06T19:35:18+08:00
[INFO] Final Memory: 20M/194M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
16:test (default-test) on project mbhd-core: There are test failures.
[ERROR]
[ERROR] Please refer to E:\workspace\multibit-hd-release-0.1.2\mbhd-core\target\
surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on projec
t mbhd-core: There are test failures.

Please refer to E:\workspace\multibit-hd-release-0.1.2\mbhd-core\target\surefire
-reports for the individual test results.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures
.

Please refer to E:\workspace\multibit-hd-release-0.1.2\mbhd-core\target\surefire
-reports for the individual test results.
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(Suref
ireHelper.java:82)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(Surefir
ePlugin.java:190)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPre
conditionsChecked(AbstractSurefireMojo.java:852)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(Abstrac
tSurefireMojo.java:720)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 20 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :mbhd-core

**Comment by gary-rowe** [comment]
Hmm, builds for me off the latest `develop` branch and Travis has a working build on Linux too.

Which test is failing?

**Comment by lamar8** [comment]
It failed just after the command "mvn install",I tried Successful both  in ubuntu and Mac OS X,but how can I make a EXE file?

**Comment by gary-rowe** [comment]
Sometimes Maven can get in a twist so here's some general build advice that may help:

* try building with `mvn clean install` on the command line off the `develop` branch for the latest code, use `master` for releases
* if you're in a hurry, use `mvn -DskipTests=true clean install` to get something off the ground

Java doesn't generally create native Windows EXE files. Instead the build creates a self-contained executable JAR file which will be named `mbhd-swing/target/multibit-hd.jar` after a successful build. You then use `java -jar <path to jar>` to run it from the command line.

If you want to create signed installers then you're better off just using the ones we've already built on the main site: https://multibit.org.

**Comment by lamar8** [comment]
Thank you very much ! I also tried "mvn clean install"  ,and failed the same reason.I just want to know how to build exe installer in windows ,or deb in linux ,dmg in OS X. It seems the original project "multibit" can build exe installer by "mvn install", but this failed. I'm not good at JAVA

**Comment by gary-rowe** [comment]
We've changed our installer technology away from IzPack which didn't allow a Java JRE to be packaged and led to a less than optimal installation experience. It also didn't work well on more modern operating systems.

Our new solution for both MultiBit HD and Classic (0.5.19+) is [Install4j](https://www.ej-technologies.com/products/install4j/overview.html). This provides a much-improved user experience and [we recommend it on our installation page](https://multibit.org/en/help/hd0.1/how-to-install-windows.html).
