### ISSUE TITLE
java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by Virosa** [bitcoin-solutions/multibit-hd#697]
Since this morning i no longer can use my wallet since it is unable to connect to the bitcoin network;

java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
	at org.multibit.hd.core.managers.HttpsManager.installCACertificates(HttpsManager.java:150)
	at org.multibit.hd.ui.views.wizards.repair_wallet.RepairWalletWizardModel$1.run(RepairWalletWizardModel.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

-----

I posted here as well; 
https://bitcointalk.org/index.php?topic=1146747.0

**Comment by gary-rowe** [comment]
Can you confirm that you've read this article: https://multibit.org/en/help/hd0.1/verify-network.html

**Comment by gary-rowe** [comment]
Quoting from your update in Bitcointalk (generally better to append more information here since we always review issues on here with priority over anywhere else):

>It was working fine yesterday. Now i tried in safe mode, checked with no firewall, still doesnt work. I added port 8333 and it is properly opened, but that doesn't fix it.
Whats up with MultiBit HD suddenly no longer connecting?
"java.net.ConnectException: Connection refused: connect"

Getting a "connection refused: connect" implies that there is a problem with your connection to the internet rather than an internal fault with MultiBit HD. It may be a general outage in your area, but if other internet services are running OK, then it is more likely to be a port routing problem. 

From the sound of it you've already addressed the port routing problem, but the reported error is associated with a repair wallet operation having trouble downloading a certificate. It would help us if we had some more detail. If you haven't reported the error through the "Help | Report error" button I'd encourage you to do so and mark it as #697 in the user comments to allow us to quickly identify it.

**Comment by Virosa** [comment]
Ugh. I found the issue, it was the wallet not properly connecting through Tor, after i disabled it, it works again. I might have messed something up Tor wise, for it not to work, or not, i don't know.

Back then it was not possible to use Report error because the wallet prevent you from closing the window during repair wallet.

If there is anything i can test/check to help, let me know.

**Comment by gary-rowe** [comment]
Thanks for the update. We've got an update to the Tor code coming in 0.1.3 but I think an extra message on the Verify network indicating this would help in the future. 

The Report error can be done a little after the fact since it encrypts and uploads the last 200Kb of logs. There's a bit more about the privacy aspect of it here: https://multibit.org/en/help/hd0.1/offline-help.html#report-error

I'll close this here since #699 will handle the UI updates.
