### ISSUE TITLE
Trying to close already closed BlockStore

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#704]
Error report id: 746098a

MultiBit HD version: 0.1.2
Operating system: 64 10.10.4 Mac OS X

No user notes

Number of stack traces: 13
First stack trace:
org.bitcoinj.store.BlockStoreException: Store closed
	at org.bitcoinj.store.SPVBlockStore.getChainHead(SPVBlockStore.java:229) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.closeBlockstore(BitcoinNetworkService.java:1504) [multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.replayWallet(BitcoinNetworkService.java:294) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager$2.call(WalletManager.java:1142) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager$2.call(WalletManager.java:1135) [multibit-hd.jar:na]
	at java.util.concur

**Comment by jim618** [comment]
This stacktrace is caused by trying to close an already closed blockstore. I have decreased the logging to a warn with no stack trace as it's not really a problem and certainly shouldn't fire the error reporter.

Awaiting review and closing

**Comment by gary-rowe** [comment]
LGTM. Closing.
