### ISSUE TITLE
Lightbox should never be called twice

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#710]
error report uploaded. Id: 25e7090

MultiBit HD version: 0.1.2
Operating system: 64 6.1 Windows 7

No user notes

Number of stack traces: 1
First stack trace:
java.lang.IllegalStateException: Light box should never be called twice 
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.components.Panels.showLightBox(Panels.java:312) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.SidebarView.handleTreeSelection(SidebarView.java:287) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.SidebarView.access$300(SidebarView.java:41) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.SidebarView$2.mouseReleased(SidebarView.java:213) ~[multibit-hd.jar:na]

**Comment by jim618** [comment]
This is easy to reproduce.
Show any light box, e.g. the Preferences | Fees lightbox.

On a Mac, go into the Application menu and chose the 'About' menu option.

Bang. CrashReporter.
