### ISSUE TITLE
NPE in filter code

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#717]
error report uploaded. Id: ebb9094

MultiBit HD version: 0.1.3
Operating system: 64 6.1 Windows 7

No user notes

Number of stack traces: 4
First stack trace:
java.lang.NullPointerException: null
	at org.multibit.hd.core.utils.DocumentMaxLengthFilter.replace(DocumentMaxLengthFilter.java:36) ~[multibit-hd.jar:na]
	at javax.swing.text.AbstractDocument.replace(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.text.JTextComponent.replaceSelection(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.text.JTextComponent.replaceInputMethodText(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.text.JTextComponent.processInputMethodEvent(Unknown Source) ~[na:1.7.0_80]

**Comment by gary-rowe** [comment]
Fixed by means of some defensive programming against unexpected null parameters.

Ready for review and close.

**Comment by jim618** [comment]
LGTM.
Closing.
