### ISSUE TITLE
mbhd.yaml not being found at wallet create

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#718]
error report uploaded. Id: 07467cf
```
MultiBit HD version: 0.1.3
Operating system: 32 6.1 Windows 7

No user notes

Number of stack traces: 1
First stack trace:
java.io.FileNotFoundException: C:\Users\*blank*\AppData\Roaming\MultiBitHD\mbhd-61c48d89-18c21e69-5e0c6178-748d0c3b-24af16ed\mbhd.yaml (Запрошенную операцию нельзя выполнить для файла с открытой пользователем сопоставленной секцией)
	at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_80]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.7.0_80]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.7.0_80]
	at org.multibit.hd.core.managers.WalletManager.updateWalletSummary(WalletManager.java:1513) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.welcome.create_wallet.CreateWalletReportPanelView.handleCreateWallet(CreateWalletReportPanelView.java:242) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.welcome.create_wallet.CreateWalletReportPanelView.access$000(CreateWalletReportPanelView.java:57) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.welcome.create_wallet.CreateWalletReportPanelView$1.run(CreateWalletReportPanelView.java:162) [multibit-hd.jar:na]
	at 
```

**Comment by gary-rowe** [comment]
Google translate of the Russian error message is:

"The requested operation can not be performed on a file with a user mapped section open"

This is a Windows-specific error (see http://stackoverflow.com/a/1302745/396747) and indicates that some other process is holding the `mbhd.yaml` open. Possibly there are two instances of MultiBit HD running and this error is getting generated during the start up phase of one of them.

**Comment by jim618** [comment]
Agreed, don't think we can fix this one.
As we want the yaml to be written out then we should fail rather than carrying on.

Closing.
