### ISSUE TITLE
java.lang.ClassCastException: javax.swing.plaf.FontUIResource cannot be cast to javax.swing.Painter

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#722]
```
error report uploaded. Id: 3368c6e

MultiBit HD version: 0.1.3
Operating system: 64 6.3 Windows 8.1

No user notes

Number of stack traces: 1
First stack trace:
java.lang.ClassCastException: javax.swing.plaf.FontUIResource cannot be cast to javax.swing.Painter
	at javax.swing.plaf.nimbus.NimbusStyle.getBackgroundPainter(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.plaf.nimbus.SynthPainterImpl.paintBackground(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.plaf.nimbus.SynthPainterImpl.paintLabelBackground(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.plaf.synth
```

**Comment by gary-rowe** [comment]
Looks like another "pure Java so can't trap it" scenario.

**Comment by jim618** [comment]
Added to list of benign exceptions.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Code review looks good.

Closing.
