### ISSUE TITLE
Multibit HD crashes when attempting to send payments or empty wallet.

### ISSUE THREAD

**Issue by rcannnon** [bitcoin-solutions/multibit-hd#725]
Bug report
  Operating System: Windows 10
  MultiBit HD Version: 0.1.3
  Steps to replicate the problem:
  When attempting to send a payment or empty wallet Multibit HD crashes.
  Screen shot:
  
![error resize](https://cloud.githubusercontent.com/assets/14361360/9976993/06cb4b1c-5ebd-11e5-8979-147fe0168ff7.png)

![error resize 2](https://cloud.githubusercontent.com/assets/14361360/9976994/130b14e8-5ebd-11e5-988d-fa3e70d66631.png)

**Comment by gary-rowe** [comment]
Thank you for uploading the error report. It's unusual for a critical failure to occur during send operations so we'll take a look and add any notes to this issue.

**Comment by jim618** [comment]
I think the problem is in saving the wallet rather than in the send.
It's this stack track:
```
First stack trace:
org.multibit.hd.core.exceptions.EncryptedFileReaderWriterException: Cannot make encrypted copy for file 'C:\Users\*blank*\AppData\Roaming\MultiBitHD\mbhd-7514553d-50c7d7a3-96b8f7f0-0288531e-770029e3\wallet8721805039629564629.tmp'
	at org.multibit.hd.core.crypto.EncryptedFileReaderWriter.encryptAndDeleteOriginal(EncryptedFileReaderWriter.java:312) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.crypto.EncryptedFileReaderWriter.makeAESEncryptedCopyAndDeleteOriginal(EncryptedFileReaderWriter.java:157) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletAutoSaveListener.onAfterAutoSave(WalletAutoSaveListener.java:65) ~[multibit-hd.jar:na]
	at org.bitcoinj.wallet.WalletFiles.saveNowInternal(WalletFiles.java:117) ~[multibit-hd.jar:na]
	at org.bitcoinj.wallet.WalletFiles.saveNow(WalletFiles.java:105) ~[multibit-hd.jar:na]
	at org.bitcoinj.core.Wallet.saveNow(Wallet.java:1424) ~[multibit-hd.jar:na]
	at org.bitcoinj.core.Wallet.freshKeys(Wallet.java:455) ~[multibit-hd.jar:na]
	at org.bitcoinj.core.Wallet.freshKey(Wallet.java:433) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.getNextChangeAddress(BitcoinNetworkService.java:1458) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.prepareTransaction(EmptyWalletWizardModel.java:234) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.empty_wallet.EmptyWalletWizardModel.showNext(EmptyWalletWizardModel.java:118) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard$6$1.run(AbstractWizard.java:391) ~[multibit-hd.jar:na]
SNIP
Caused by: java.io.FileNotFoundException: C:\Users\*blank*\AppData\Roaming\MultiBitHD\mbhd-7514553d-50c7d7a3-96b8f7f0-0288531e-770029e3\mbhd.wallet.aes (Access is denied)
	at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_80]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.7.0_80]
	at java.io.FileOutputStream.<init>(Unknown Source) ~[na:1.7.0_80]
	at org.multibit.hd.core.crypto.EncryptedFileReaderWriter.encryptAndDeleteOriginal(EncryptedFileReaderWriter.java:298) ~[multibit-hd.jar:na]
	... 25 common frames omitted
```
There is an 'access is denied' in the above which suggests something like a file lock that isn't released or something similar.


If your wallet is a regular MultiBit HD wallet, rather than a Trezor wallet, to retrieve your bitcoins the simplest way will be to:
1) Download lighthouse from https://www.vinumeris.com/lighthouse
2) Create a new wallet using your wallet words (they are compatible)
3) Wait for the wallet to sync and then empty the wallet to whereever you want.

**Comment by rcannnon** [comment]
Thank you for the help, it's very much appreciated.

**Comment by angra84** [comment]
Hello, I have the same problem and after installing and running lighthouse the only thing multibit asked me to do was to send this new wallet the existing balance, but it all appeared to be zero. This transaction has now more than 2 hours since placed and it's still on error, C'mon I need to complete this transaction.

**Comment by angra84** [comment]
when I'm installing the lighthouse software it does not allow me to restore my multibit wallet in order to sync it with this one,

**Comment by angra84** [comment]
Finally it worked, and thanks so much for your comment
