### ISSUE TITLE
java.lang.ClassCastException: sun.awt.Win32GraphicsConfig cannot be cast to sun.java2d.d3d.D3DGraphicsConfig

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#735]
error report uploaded. Id: c483c51

MultiBit HD version: 0.1.3
Operating system: 64 6.2 Windows 8

User notes length: 39

Number of stack traces: 2
First stack trace:
java.lang.ClassCastException: sun.awt.Win32GraphicsConfig cannot be cast to sun.java2d.d3d.D3DGraphicsConfig
	at sun.java2d.d3d.D3DSurfaceData.makeProxyFor(Unknown Source) ~[na:1.7.0_80]
	at sun.java2d.SurfaceData.getSourceSurfaceData(Unknown Source) ~[na:1.7.0_80]
	at sun.java2d.pipe.DrawImage.renderImageCopy(Unknown Source) ~[na:1.7.0_80]
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source) ~[na:1.7.0_80]
	at sun.java2d.pipe.DrawImage.copyImage(Unknown Source) ~[na:1.7.0_80]
	at sun.java2d.pipe.ValidatePipe.copyImage(Unknown Source) ~[na:1.7.0_80]
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source) ~[na:1.7.0_80]
	at sun.java2d.SunGraphics2D.drawImage(Unknown Source) ~[na:1.7.0_80]
	at org.multibit.hd.ui.views.components.panels.BackgroundPanel.drawActual(BackgroundPanel.java:191) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.components.panels.BackgroundPanel.paintComponent(BackgroundPanel.java:252) ~[multibit-hd.jar:na]

**Comment by gary-rowe** [comment]
Another one for the "benign list" since we can't predict the failure at this level.

**Comment by jim618** [comment]
Added to ExceptionHandler isBenign().

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Sad that we have to do this, but the code will correctly trap the condition.

Closing.
