### ISSUE TITLE
BlockStoreException: Header bytes do not equal SPVB

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#740]
error report uploaded. Id: 4edef02
```
MultiBit HD version: 0.1.3
Operating system: 64 6.3 Windows 8.1

User notes length: 54

Number of stack traces: 3
First stack trace:
org.bitcoinj.store.BlockStoreException: org.bitcoinj.store.BlockStoreException: Header bytes do not equal SPVB
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:131) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.BlockStoreManager.createOrOpenBlockStore(BlockStoreManager.java:80) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.openBlockStore(BitcoinNetworkService.java:182) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.checkIfWalletNeedsToSync(WalletManager.java:834) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.updateConfigurationAndCheckSync(WalletManager.java:791) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.openWalletFromWalletId(WalletManager.java:254) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.checkPasswordAndLoadWallet(CredentialsWizardModel.java:784) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.access$500(CredentialsWizardModel.java:57) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$10.call(CredentialsWizardModel.java:711) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$10.call(CredentialsWizardModel.java:703) [multibit-hd.jar:na]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_80]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_80]
Caused by: org.bitcoinj.store.BlockStoreException: Header bytes do not equal SPVB
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:121) ~[multibit-hd.jar:na]
	... 13 common frames omitted
```
Should be able to recover from this by nuking the blockstore and creating a new one

**Comment by jim618** [comment]
I've tidied up the code slightly so that a couple of stack traces that are diagnostic have become messages. The recovery code as suggested in the post above was already in place.

This error report needs looking at in more detail as there may be another problem later in the report.

**Comment by jim618** [comment]
This can be reviewed and closed as is - no need to delay.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
