### ISSUE TITLE
VerifyMessage needs to be more resilient

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#744]
Error report indicates bad signature crashes app - should be more resilient.

error report uploaded. Id: 1691011
```
MultiBit HD version: 0.1.3
Operating system: 64 6.3 Windows 8.1

User notes length: 233

Number of stack traces: 1
First stack trace:
java.security.SignatureException: Signature truncated, expected 65 bytes and got 12
	at org.bitcoinj.core.ECKey.signedMessageToKey(ECKey.java:887) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.verifyMessage(WalletManager.java:1747) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.verify_message.VerifyMessagePanelView.verifyMessage(VerifyMessagePanelView.java:233) [multibit-hd.jar:na]
	at 
```

**Comment by jim618** [comment]
This exception was already being caught.
I have downgraded the logging to just class + message to avoid a stack trace being picked up by the error reporter.

Tested that a truncated signature gives the correct UI response ok.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
