### ISSUE TITLE
Crash on org.bitcoinj.net.discovery.PeerDiscoveryException

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#747]
error report uploaded. Id: 9f5165c
```
MultiBit HD version: 0.1.3
Operating system: 64 6.3 Windows 8.1

No user notes

Number of stack traces: 31
First stack trace:
org.bitcoinj.net.discovery.PeerDiscoveryException: No peer discovery returned any results: check internet connection?
	at org.bitcoinj.net.discovery.MultiplexingDiscovery.getPeers(MultiplexingDiscovery.java:85) ~[multibit-hd.jar:na]
	at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:788) ~[multibit-hd.jar:na]
	at org.bitcoinj.core.PeerGroup$5.go(PeerGroup.java:497) [multibit-hd.jar:na]
	at org.bitcoinj.core.PeerGroup$5.run(PeerGroup.java:468) [multibit-hd.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_80]
```
MBHD should not crash in this situation - it is expected if there is no network connection

**Comment by jim618** [comment]
As this is thrown on a PeerGroup executor thread there is not much we can do to intercept this except add it to the ExceptioHandler as benign.

There is a separate issue highlighting the need for better feedback on poor Bitcoin network connectivity which will include the side effect of this (no Bitcoin network connection). It is also shown clearly on the UI in the bottom right corner status RAG.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
