### ISSUE TITLE
javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to java.awt.Font

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#754]
java.lang.ClassCastException: javax.swing.plaf.nimbus.DerivedColor$UIResource cannot be cast to java.awt.Font
	at javax.swing.plaf.nimbus.NimbusStyle.getFontForState(NimbusStyle.java:573) ~[na:1.8.0_66-internal]
	at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:933) ~[na:1.8.0_66-internal]
	at javax.swing.plaf.nimbus.NimbusStyle.installDefaults(NimbusStyle.java:231) ~[na:1.8.0_66-internal]
	at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:916) ~[na:1.8.0_66-internal]
	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:265) ~[na:1.8.0_66-internal]

Another one to add to the list of benign exceptions.

**Comment by jim618** [comment]
Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
