### ISSUE TITLE
Could not decrypt should not invoke ErrorReporter

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#792]
```
[2015-10-13T21:24:05.377-04:00] DEBUG safe-fixed-unlock-wallet-0 org.multibit.hd.core.managers.BackupManager - Application data directory
'/Users/*blank*/Library/Application Support/MultiBitHD'
[2015-10-13T21:24:05.880-04:00] ERROR safe-fixed-unlock-wallet-0 org.multibit.hd.core.managers.BackupManager - Could not load rolling backup:
'/Users/*blank*/Library/Application Support/MultiBitHD/mbhd-6e4cb4f6-ab78ca1d-463756e3-8ee4adbd-61de6e4b/rolling-backup/mbhd-20150622180449.wallet.aes'

org.bitcoinj.crypto.KeyCrypterException: Could not decrypt: pad block corrupted
	at org.multibit.commons.crypto.AESUtils.decrypt(AESUtils.java:127) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.loadWalletFromFile(WalletManager.java:954) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.BackupManager.loadRollingBackup(BackupManager.java:427) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.loadFromWalletDirectory(WalletManager.java:1079) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.openWalletFromWalletId(WalletManager.java:249) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.checkPasswordAndLoadWallet(CredentialsWizardModel.java:784) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.access$500(CredentialsWizardModel.java:57) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$10.call(CredentialsWizardModel.java:711) [multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel$10.call(CredentialsWizardModel.java:703) [multibit-hd.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: org.spongycastle.crypto.InvalidCipherTextException: pad block corrupted
	at org.spongycastle.crypto.paddings.PKCS7Padding.padCount(PKCS7Padding.java:63) ~[multibit-hd.jar:na]
	at org.spongycastle.crypto.paddings.PaddedBufferedBlockCipher.doFinal(PaddedBufferedBlockCipher.java:287) ~[multibit-hd.jar:na]
	at org.multibit.commons.crypto.AESUtils.decrypt(AESUtils.java:118) ~[multibit-hd.jar:na]
	... 12 common frames omitted
```
Require better reporting to the user

**Comment by jim618** [comment]
Checking the BackupManager, this is just error logging and not the cause of the error report.
I've simplified the logging so that only the class + message is listed so the error reporter will skip this stack trace and show the next, hopefully 'real' error.

Checked by entering wrong password (to a wallet without contacts, as they are loaded first as a quick-fail-check)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
