### ISSUE TITLE
NPE in savePaymentRequest

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#798]
```
[2015-10-19T20:55:44.505+08:00] ERROR AWT-EventQueue-0 org.multibit.hd.core.error_reporting.ExceptionHandler - Uncaught exception. Proceeding to show Error Reporting dialog...

java.lang.NullPointerException: null
	at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.savePaymentRequest(RequestBitcoinEnterDetailsPanelView.java:245) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.beforeHide(RequestBitcoinEnterDetailsPanelView.java:212) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard.hide(AbstractWizard.java:226) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard$3.actionPerformed(AbstractWizard.java:312) ~[multibit-hd.jar:na]
	at javax.swing.SwingUtilities.notifyAction(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.JComponent.processKeyBinding(Unknown Source) ~[na:1.7.0_80]
```
Possible race condition during hide.

**Comment by jim618** [comment]
Added in null checking on getRate here and in a couple of other places in the code.

Awaiting code review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
