### ISSUE TITLE
Push of data element larger than element in setFiatEquivalent

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#799]
```
java.lang.RuntimeException: org.bitcoinj.core.ScriptException: Push of data element that is larger than remaining data
	at org.bitcoinj.core.TransactionOutput.toString(TransactionOutput.java:360) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.setFiatEquivalent(BitcoinNetworkService.java:848) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.prepareTransaction(BitcoinNetworkService.java:762) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.send_bitcoin.SendBitcoinWizardModel.prepareTransaction(SendBitcoinWizardModel.java:454) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.send_bitcoin.SendBitcoinWizardModel.prepareWhenBIP70(SendBitcoinWizardModel.java:920) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.payments.BIP70PaymentRequestDetailPanelView$1.actionPerformed(BIP70PaymentRequestDetailPanelView.java:280) ~[multibit-hd.jar:na]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.7.0_80]
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source) ~[na:1.7.0_80]
```
Insufficient defensive checking during BIP 70 payment.

**Comment by jim618** [comment]
There was a transactionOutput.toString() outside a try- catch. Fixed.
Also converted a transactionOutput.toString in logging to log the hash which should always be computable.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Bouncing back due to missing {} notation - nitpicking I know but consistency is important.

**Comment by jim618** [comment]
Updated to use {} notation.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Looks good to me. Closing.
