### ISSUE TITLE
Illegal argument exception in icon create

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#802]
java.lang.IllegalArgumentException: Width (0) and height (276) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source) ~[na:1.7.0_80]
	at java.awt.GraphicsConfiguration.createCompatibleImage(Unknown Source) ~[na:1.7.0_80]
	at org.multibit.hd.ui.views.components.ImageDecorator.toBufferedImage(ImageDecorator.java:77) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.components.ImageDecorator.toImageIcon(ImageDecorator.java:114) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.components.Panels.newDetailBackgroundPanel(Panels.java:213) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizardPanelView.<init>(AbstractWizardPanelView.java:133) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.payments.TransactionOverviewPanelView.<init>(TransactionOverviewPanelView.java:64) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.payments.PaymentsWizard.populateWizardViewMap(PaymentsWizard.java:32) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard.<init>(AbstractWizard.java:117) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard.<init>(AbstractWizard.java:80) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.payments.PaymentsWizard.<init>(PaymentsWizard.java:25) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.Wizards.newPaymentsWizard(Wizards.java:473) ~[multibit-hd.jar:na]

**Comment by jim618** [comment]
Dupe
