### ISSUE TITLE
NPE in savePaymentRequest

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#803]
Also looked like there was a bad network connection
```
java.lang.NullPointerException: null
	at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.savePaymentRequest(RequestBitcoinEnterDetailsPanelView.java:245) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.beforeHide(RequestBitcoinEnterDetailsPanelView.java:212) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard.hide(AbstractWizard.java:226) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard$3.actionPerformed(AbstractWizard.java:312) ~[multibit-hd.jar:na]
	at javax.swing.SwingUtilities.notifyAction(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.JComponent.processKeyBinding(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.JComponent.processKeyBindings(Unknown Source) ~[na:1.7.0_80]
	at javax.swing.JComponent.processKeyEvent(Unknown Source) ~[na:1.7.0_80]
	at java.awt.Component.processEvent(Unknown Source) ~[na:1.7.0_80]
	at java.awt.Container.processEvent(Unknown Source) ~[na:1.7.0_80]
	at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.7.0_80]
	at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.7.0_80]
```

**Comment by jim618** [comment]
Dupe of #798.

Closing.
