### ISSUE TITLE
Unable to start HidApi: Java heap space

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#809]
```
org.hid4java.HidException: Unable to start HidApi: Java heap space
	at org.hid4java.HidDeviceManager.getAttachedHidDevices(HidDeviceManager.java:235) ~[multibit-hd.jar:na]
	at org.hid4java.HidDeviceManager.scan(HidDeviceManager.java:163) ~[multibit-hd.jar:na]
	at org.hid4java.HidDeviceManager$1.run(HidDeviceManager.java:133) ~[multibit-hd.jar:na]
	at java.lang.Thread.run(Unknown Source) ~[na:1.7.0_80]
```

**Comment by savioroshan** [comment]
Can anyone help me, when i to send my bitcoins through multibit HD i am getting error message unable to start Hidapi java heap space. what should i need to do.
