### ISSUE TITLE
Lightbox should not be seen twice with About app

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#813]
```
[2015-11-13T18:52:04.409+01:00] ERROR AWT-EventQueue-0 org.multibit.hd.core.error_reporting.ExceptionHandler - Uncaught exception. Proceeding to show Error Reporting dialog...

java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy15.handleAbout(Unknown Source) ~[na:na]
	at com.apple.eawt._AppEventHandler$_AboutDispatcher.performUsing(_AppEventHandler.java:250) ~[na:1.7.0_80]
	at com.apple.eawt._AppEventHandler$_AboutDispatcher.performUsing(_AppEventHandler.java:244) ~[na:1.7.0_80]
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:516) ~[na:1.7.0_80]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312) ~[na:1.7.0_80]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745) ~[na:1.7.0_80]
	at java.awt.EventQueue.access$300(EventQueue.java:103) ~[na:1.7.0_80]
	at java.awt.EventQueue$3.run(EventQueue.java:706) ~[na:1.7.0_80]
	at java.awt.EventQueue$3.run(EventQueue.java:704) ~[na:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76) ~[na:1.7.0_80]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715) ~[na:1.7.0_80]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242) [na:1.7.0_80]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161) [na:1.7.0_80]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150) [na:1.7.0_80]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146) [na:1.7.0_80]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138) [na:1.7.0_80]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91) [na:1.7.0_80]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_80]
	at org.multibit.hd.ui.platform.builder.mac.BaseMacInvocationHandler.invoke(BaseMacInvocationHandler.java:81) ~[multibit-hd.jar:na]
	... 18 common frames omitted
Caused by: java.lang.IllegalStateException: Light box should never be called twice 
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.components.Panels.showLightBox(Panels.java:313) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.controllers.MainController.onAboutEvent(MainController.java:777) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.platform.handler.DefaultAboutHandler.handleAbout(DefaultAboutHandler.java:66) ~[multibit-hd.jar:na]
	... 23 common frames omitted
```

**Comment by jim618** [comment]
You can replicate this on a Mac by:
1) Showing a lightbox e.g. showing the transaction details wizard.
2) Going to the application menu and doing About MultiBit HD.
3) CrashReporter is shown

**Comment by jim618** [comment]
Near dupe of #710
