### ISSUE TITLE
Java Connection Refused

### ISSUE THREAD

**Issue by 17thatch** [bitcoin-solutions/multibit-hd#814]
Bug report
  Operating System: Windows 10 Home
  MultiBit HD Version: 0.1.4
  Steps to replicate the problem:
  1. Provide steps to reproduce
1. Attempt to open application 
2. No response (except increased processor usage)
This error appears at file location:
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
	at org.multibit.hd.core.managers.HttpsManager.installCACertificates(HttpsManager.java:150)
	at org.multibit.hd.ui.views.wizards.repair_wallet.RepairWalletWizardModel$1.run(RepairWalletWizardModel.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

3. And yes... I manually opened port 8333
- I don't use Tor
- The program worked yesterday

**Comment by jim618** [comment]
That thread (HttpsManager) is refreshing the SSL certificates used to connect to exchanges.

Does the user interface appear ?
It should be a background task (which looks like it is having trouble getting through to an exchange) that shouldn't affect the UI appearing.

**Comment by 17thatch** [comment]
The user interface does not appear... although I haven't checked if it is
running in the background or not.

**Comment by 17thatch** [comment]
How would you go about refreshing the SSL certificate?

**Comment by jim618** [comment]
It should be automatic. When the user does a Manage Wallet | Repair wallet it does it then too

Are there any other errors in the log?

**Comment by 17thatch** [comment]
These are the errors:

java.net.ConnectException: Connection refused: connect
at java.net.DualStackPlainSocketImpl.connect0(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
at sun.security.ssl.SSLSocketImpl.<init>(Unknown Source)
at sun.security.ssl.SSLSocketFactoryImpl.createSocket(Unknown Source)
at
org.multibit.hd.core.managers.HttpsManager.installCACertificates(HttpsManager.java:150)
at
org.multibit.hd.ui.views.wizards.repair_wallet.RepairWalletWizardModel$1.run(RepairWalletWizardModel.java:92)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by 17thatch** [comment]
Also, it doesn't run in the background.
