### ISSUE TITLE
NPE in SendRequestSummary#getTotalAmount

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#831]
Error report uploaded. Id: 196f490

```
MultiBit HD version: 0.1.4
Operating system: 64 6.3 Windows 8.1

No user notes

Number of stack traces: 1
First stack trace:
java.lang.NullPointerException: null
	at org.multibit.hd.core.dto.SendRequestSummary.getTotalAmount(SendRequestSummary.java:118) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.completeWithoutSigning(BitcoinNetworkService.java:939) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.prepareTransaction(BitcoinNetworkService.java:767) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.send_bitcoin.SendBitcoinWizardModel.prepareTransaction(SendBitcoinWizardModel.java:467) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.send_bitcoin.SendBitcoinWizardModel.prepareWhenBIP70(SendBitcoinWizardModel.java:970) ~[multibit-hd.jar:na]
```

**Comment by jim618** [comment]
I have added in some defensive coding against an NPE in getTotalAmount.
There are various other calls to this method in BitcoinNetwrokService but it's not clear the root cause of this error so I will leave that to future error reports to highlight (if it is a problem).

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Bouncing back to trigger a second code review.

**Comment by jim618** [comment]
Updated code to improve NPE hardness.

Awaiting review and closing

**Comment by gary-rowe** [comment]
Verified working. Closing.
