### ISSUE TITLE
Error in browser when viewing help

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#849]
First stack trace:
java.io.IOException: Failed to open https://multibit.org/hd0.1/contents.html. Error message: Присоединенное к системе устройство не работает (Google translation: Attached to the system unit does not work).

	at sun.awt.windows.WDesktopPeer.ShellExecute(Unknown Source) ~[na:1.7.0_80]
	at sun.awt.windows.WDesktopPeer.browse(Unknown Source) ~[na:1.7.0_80]
	at java.awt.Desktop.browse(Unknown Source) ~[na:1.7.0_80]
	at org.multibit.hd.ui.utils.SafeDesktop.browse(SafeDesktop.java:44) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.screens.help.HelpScreenView$8.actionPerformed(HelpScreenView.java:564) [multibit-hd.jar:na]

**Comment by gary-rowe** [comment]
This could be a false positive. Looking at the code, [SafeDesktop#44](https://github.com/bitcoin-solutions/multibit-hd/blob/develop/mbhd-swing/src/main/java/org/multibit/hd/ui/utils/SafeDesktop.java#L44) already has `IOException` handling in place. 

Suggest this be closed since there is no action that we can take. His system has rejected allowing Java to open an external browser.

**Comment by jim618** [comment]
Fair enough.
A locked down system probably won't allow such a thing so it's not really a bug but the OS doing it's thing.
Closing
