### ISSUE TITLE
Class cast failure in CredentialsWizardModel.showOperationFailed

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#853]
Looks like an unexpected class being returned which makes a class cast go bang

```
 error report uploaded. Id: 57a7340

MultiBit HD version: 0.1.4
Operating system: 64 2.6.32-358.11.1.el6.centos.plus.x86_64 Linux

User notes length: 258

Number of stack traces: 2
First stack trace:
java.lang.ClassCastException: org.multibit.hd.hardware.core.messages.Features cannot be cast to org.multibit.hd.hardware.core.messages.Failure
	at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.showOperationFailed(CredentialsWizardModel.java:364) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractHardwareWalletWizard$9.run(AbstractHardwareWalletWizard.java:348) ~[multibit-hd.jar:na]
```

**Comment by gary-rowe** [comment]
Fixed as side effect of #837 (see [b51ef653](https://github.com/bitcoin-solutions/multibit-hd/commit/b51ef653b02b2c4899131c23f17d91fcd6d3b338))

Closing.
