### ISSUE TITLE
Rolling backup code needly more resilience

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#857]
The rolling backup code isn't resilient to users renaming/ copying rolling back files (why they would do that who knows)
```
MultiBit HD version: 0.2.0
Operating system: 64 6.3 Windows 8.1

No user notes

Number of stack traces: 1
First stack trace:
java.lang.IllegalArgumentException: Rolling backup files are in the wrong format. Error = 'Invalid format: "bit-2014012018"'
	at org.multibit.hd.core.managers.BackupManager.getRollingBackups(BackupManager.java:226) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.BackupManager.createRollingBackup(BackupManager.java:292) [multibit-hd.jar:na]
	at org.multibit.hd.core.services.BackupService.performRollingBackup(BackupService.java:250) [multibit-hd.jar:na]
	at org.multibit.hd.core.services.BackupService.access$300(BackupService.java:58) [multibit-hd.jar:na]
	at org.multibit.hd.core.services.BackupService$1.run(BackupService.java:163) [multibit-hd.jar:na]	
```

**Comment by gary-rowe** [comment]
Hmmm, users aren't supposed to be renaming those internal files. This is akin to trying to locate a renamed `mbhd.yaml` file. Not sure we should be trying to second guess their actions here.

Moving to Discussion milestone until we decide to push forward.

**Comment by jim618** [comment]
Users shouldn't be changing those files no.
I recommend we upgrade the filtering so that only files of the right format are used and the rest ignored.
At the moment if there are 'other files' the IllegalArgumentException gets thrown all the way up the stack which seems a bit drastic.
