### ISSUE TITLE
BlockStore file locked

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#866]
error report uploaded. Id: 4a0ee5b

MultiBit HD version: 0.2.0
Operating system: 64 6.3 Windows 8.1

User notes length: 73

Number of stack traces: 5
First stack trace:
org.bitcoinj.store.BlockStoreException: org.bitcoinj.store.ChainFileLockedException: Store file is already locked by another process
	at org.bitcoinj.store.SPVBlockStore.<init>(SPVBlockStore.java:131) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.BlockStoreManager.createOrOpenBlockStore(BlockStoreManager.java:71) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.openBlockStore(BitcoinNetworkService.java:190) [multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.replayWallet(BitcoinNetworkService.java:348) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager$2.call(WalletManager.java:1165) [multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager$2.call(WalletManager.java:1158) [multibit-hd.jar:na]

**Comment by ahamroun** [comment]
Hi,
Did you find answers to this problem?
