### ISSUE TITLE
BlockStoreException: Corrupted block store: could not find chain head

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#873]
Exception opening blockstore - can recover by nuking BlockStore,
```
 error report uploaded. Id: 76a926e

MultiBit HD version: 0.2.0
Operating system: 32 6.1 Windows 7

No user notes

Number of stack traces: 4
First stack trace:
org.bitcoinj.store.BlockStoreException: Corrupted block store: could not find chain head: 00000000000000000427e829438caa597e04b4ddf4eb1a95c24c56767f5112c3
	at org.bitcoinj.store.SPVBlockStore.getChainHead(SPVBlockStore.java:240) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.services.BitcoinNetworkService.openBlockStore(BitcoinNetworkService.java:202) ~[multibit-hd.jar:na]
	at org.multibit.hd.core.managers.WalletManager.checkIfWalletNeedsToSync(WalletManager.java:841) [multibit-hd.jar:na]
	at 
```

**Comment by jim618** [comment]
I have update BlockStoreManager to delete the blockstore file if this (or similar) error is encountered.
You can test this by intentionally damaging the mbhd.spvchain file.

Pushed to the debrit branch.

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
