### ISSUE TITLE
Could not create directory: 'null\MultiBitHD'

### ISSUE THREAD

**Issue by AlienLifeForm1** [bitcoin-solutions/multibit-hd#896]
I've installed MultiBid HD for the first time on Windows 7 Home x64. I'm getting the following error:

`java.lang.IllegalStateException: Could not create directory: 'null\MultiBitHD'
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.multibit.commons.files.SecureFiles.verifyOrCreateDirectory(SecureFiles.java:196)
	at org.multibit.hd.core.managers.InstallationManager.getOrCreateApplicationDataDirectory(InstallationManager.java:170)
	at org.multibit.hd.core.config.LoggingConfiguration$FileConfiguration.<init>(LoggingConfiguration.java:186)
	at org.multibit.hd.core.logging.LoggingFactory.bootstrap(LoggingFactory.java:41)
	at org.multibit.hd.ui.MultiBitHD.start(MultiBitHD.java:120)
	at org.multibit.hd.ui.MultiBitHD.main(MultiBitHD.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:101)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:16)
`

**Comment by gary-rowe** [comment]
This looks like you don't have admin privileges on your machine, or you cannot see your local user account for some reason.
